# Generated by Django 3.2.7 on 2021-10-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dotaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Titul dotazu')),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Poddotaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Titul poddotazu')),
                ('dotaz', models.ManyToManyField(to='portalhelpdesk.Dotaz')),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
    ]
